/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    ArgonAlert: typeof import('./../components/ArgonAlert.vue')['default']
    ArgonAvatar: typeof import('./../components/ArgonAvatar.vue')['default']
    ArgonBadge: typeof import('./../components/ArgonBadge.vue')['default']
    ArgonButton: typeof import('./../components/ArgonButton.vue')['default']
    ArgonCheckbox: typeof import('./../components/ArgonCheckbox.vue')['default']
    ArgonInput: typeof import('./../components/ArgonInput.vue')['default']
    ArgonPagination: typeof import('./../components/ArgonPagination.vue')['default']
    ArgonPaginationItem: typeof import('./../components/ArgonPaginationItem.vue')['default']
    ArgonProgress: typeof import('./../components/ArgonProgress.vue')['default']
    ArgonRadio: typeof import('./../components/ArgonRadio.vue')['default']
    ArgonSnackbar: typeof import('./../components/ArgonSnackbar.vue')['default']
    ArgonSocialButton: typeof import('./../components/ArgonSocialButton.vue')['default']
    ArgonSwitch: typeof import('./../components/ArgonSwitch.vue')['default']
    ArgonTextarea: typeof import('./../components/ArgonTextarea.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
